### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by skylord123** [mbolotov/k6-intellij-plugin#10]
This plugin causes PHPStorm to freeze for a few seconds whenever I right click a file. Also caused my xdebug sessions to be unusable.

This may have something to do with my projects being in WSL.

**Comment by mbolotov** [comment]
Hi @skylord123 ?
could you check if this is reproducible on `1.0.1`?
if yes, could you provide any repository to reproduce the issue?

**Comment by mbolotov** [comment]
closing as no response received in 2 months,
please create a new issue if the problem persists
