### ISSUE TITLE
Debug not available

### ISSUE THREAD

**Issue by ihandley-efx** [mbolotov/k6-intellij-plugin#15]
1. I understand debugging is a feature of the paid version. However, I selected the `Free trial` option, and I still don't see the `debug` option come up.
2. I don't see an option to buy the paid version

Thanks in advance for your help.

**Comment by mbolotov** [comment]
Hi Ian,
> I understand debugging is a feature of the paid version. However, I selected the Free trial option, and I still don't see the debug option come up.

Could you please attach a screenshot/video showing the problem?

Does `Licenses` window show `k6` plugin as active at your setup?
![image](https://github.com/user-attachments/assets/50456606-6271-42a9-af84-1d0810aca61b)
Also, for performance reasons, the plugin checks the active status no more than once every 5 minutes. So after activation of your k6 license, you should either wait for 5 minutes or restart the IDE. I will try to rework this behavior in the next plugin version.

> I don't see an option to buy the paid version

You need to log in to your [JetBrains account](https://account.jetbrains.com) and buy a license there. 
Please refer to the official guide here: https://www.jetbrains.com/help/idea/register.html#activate-license

**Comment by ihandley-efx** [comment]
Thanks for your quick response!

Here is a screenshot of my licenses window. As you can see, K6 shows as activated:
<img width="601" alt="image" src="https://github.com/user-attachments/assets/daacd641-0c3f-47bf-8b44-b3e0ee2c2a1f">

Here is a video of what happens when I press the "play" button. The expected behavior is I would get an option to run as normal or run in debug mode, but as you can see, I don't get that option, and it just runs K6 as normal.
![2024-08-22_10-25-55 (2)](https://github.com/user-attachments/assets/f41f9293-4335-44d3-a6c9-313aedf30bd2)

Please disregard my comment about being unable to purchase. It was due to a mistake on my end.

Thanks again!

**Comment by mbolotov** [comment]
First, the same behavior is actual for the older version of plugin (before 1.1.0). Could you check the version? You can find it in the `Settings -> Plugins` :
![image](https://github.com/user-attachments/assets/1f92c96a-ffc1-4cfc-b00b-b590d531e785)

Also, how does the 'Debug' icon look like?
![image](https://github.com/user-attachments/assets/5d656eb0-90ba-49cc-aeab-bcf47fa98d04)

**Comment by ihandley-efx** [comment]
Good call. It looks like I have version 1.0.3. 
<img width="263" alt="image" src="https://github.com/user-attachments/assets/c61d46fb-f03c-422c-91b1-a6b4e8481461">

Here's my debug button. As you can see, it's disabled.
<img width="167" alt="image" src="https://github.com/user-attachments/assets/5cc81619-779d-401f-a78c-1fee3adbe4f7">

**Comment by mbolotov** [comment]
yep. Disabled debug button is expected for 1.0.3 version. Please update to the latest one.

**Comment by ihandley-efx** [comment]
I had to upgrade my version of Jetbrains to support the new plugin version, but it now works as expected. Thanks so much!
