### ISSUE TITLE
K6 prevent rename package name in a java project.

### ISSUE THREAD

**Issue by topikachu** [mbolotov/k6-intellij-plugin#17]
I can't rename the java package after installing K6 plugin.

java.lang.NullPointerException:  must not be null
	at io.k6.ide.plugin.lang.q.canProcessElement(SourceFile:243)
	at com.intellij.refactoring.rename.RenamePsiElementProcessor.allForElement(RenamePsiElementProcessor.java:44)
	at com.intellij.refactoring.rename.RenameProcessor.prepareRenaming(RenameProcessor.java:130)
	at com.intellij.refactoring.rename.RenameProcessor.doRun(RenameProcessor.java:124)
	at com.intellij.refactoring.BaseRefactoringProcessor.lambda$run$13(BaseRefactoringProcessor.java:604)
	at com.intellij.refactoring.BaseRefactoringProcessor.run(BaseRefactoringProcessor.java:620)

Below is the system info after disable K6

IntelliJ IDEA 2024.1.7 (Ultimate Edition)
Build #IU-241.19416.15, built on October 16, 2024
Licensed to XXXX

Runtime version: 17.0.12+1-b1207.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
  ide.experimental.ui=true
  editor.minimap.enabled=true
  go.run.processes.with.pty=false
Non-Bundled Plugins:
  PsiViewer (241.14494.158-EAP-SNAPSHOT)
  zzccctv.Pulsaride (2023.1.2)
  aws.toolkit.core (3.33-241)
  de.netnexus.camelcaseplugin (3.0.12)
  com.samvtran.plugins.macosforallkeymap (3.0.0)
  org.jetbrains.plugins.go-template (241.14494.150)
  name.kropp.intellij.makefile (241.14494.150)
  org.plugin.dot.id (1.5.4)
  org.jetbrains.plugins.go (241.18968.26)
  com.tabnine.TabNine (1.150.0)
  Pythonid (241.19416.15)
  com.opentext.sma.smaxtool (1.0-SNAPSHOT)
  dev.turingcomplete.intellijbytecodeplugin (4.2.1)
  mobi.hsz.idea.gitignore (4.5.4)
  org.exbin.deltahex.intellij (0.2.10.1)
  com.intellij.bigdatatools.core (241.19416.15)
  com.intellij.bigdatatools.kafka (241.14494.158)
  com.intellij.bigdatatools.binary.files (241.14494.158)
  com.intellij.bigdatatools.rfs (241.19416.15)
  com.intellij.bigdatatools.metastore.core (241.14494.158)
  com.intellij.bigdatatools.flink (241.14494.158)
  intellij.jupyter (241.18968.26)
  aws.toolkit (3.33-241)
  com.intellij.bigdatatools.spark (241.15989.21)
  com.intellij.bigdatatools.zeppelin (241.17890.1)
  com.intellij.bigdatatools (241.14494.158)
Kotlin: 241.19416.15-IJ

**Comment by mbolotov** [comment]
Hi, 
could you try this bundle with the fix?
[k6-1.2.2-EAP-1.zip](https://github.com/user-attachments/files/17472591/k6-1.2.2-EAP-1.zip)

**Comment by mbolotov** [comment]
fixed in `1.2.2` version
