### ISSUE TITLE
Cannot find module node_modules/k6-debug-api/data.js

### ISSUE THREAD

**Issue by AndrewASel** [mbolotov/k6-intellij-plugin#18]
Use in script:
import { SharedArray } from 'k6/data';

Try to run test with debug
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Waiting for the debugger to disconnect...
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/node_modules/k6-debug-api/data.js'

**Comment by mbolotov** [comment]
Hi @AndrewASel,
please bump the version of `k6-debug-api` module to `1.2.0` in your project. I've fixed this problem within the module.
