### ISSUE TITLE
Option User agent is changed to K6 during running debug

### ISSUE THREAD

**Issue by AndrewASel** [mbolotov/k6-intellij-plugin#20]
Specify own User agent
https://grafana.com/docs/k6/latest/using-k6/k6-options/reference/#user-agent
For example
`userAgent: "ownUserAgent",`

Run test with debug:
It changed to K6 user agent

![image](https://github.com/user-attachments/assets/f948c867-44ea-4110-80ea-6bfb74159c1e)

If run without debug it use specified user agent

**Comment by mbolotov** [comment]
Hi @AndrewASel 
Could you try this bundle with the fix? 
[k6-1.2.3.zip](https://github.com/user-attachments/files/17587657/k6-1.2.3.zip)
You must also update the `k6-debug-api` module to `1.4.0` version in your project

**Comment by AndrewASel** [comment]
Hello @mbolotov
I run test with debug, plugin version 1.2.3 and k6-debug-api version 1.4.0
Confirm that this issue has been fixed

**Comment by mbolotov** [comment]
fixed in `1.3.0`
