### ISSUE TITLE
New Date() returns different format for RUN/DEBUG 

### ISSUE THREAD

**Issue by AndrewASel** [mbolotov/k6-intellij-plugin#21]
During run test 
`new Date()` returns 2024-10-31T22:42:19.356Z

During debug test 
`new Date()` returns: Thu Oct 31 2024 18:42:19 GMT-0400 (Eastern Daylight Time)

![image](https://github.com/user-attachments/assets/d8f39ff7-2689-454f-b2d8-f6483534ee8c)

**Comment by mbolotov** [comment]
That's strange.
Can you check if you have some additional settings in k6 that could affect the date formatting?
I'm unable to reproduce it using a common setup:
![image](https://github.com/user-attachments/assets/9cb5e015-a028-4925-b92a-55acd3b0aae5)

and this is for debugging:
`Current date: Fri Nov 01 2024 10:08:05 GMT+0300 (GMT+03:00)`

**Comment by mbolotov** [comment]
could you share a project to reproduce?

**Comment by AndrewASel** [comment]
Hello @mbolotov 
It definitely strange, I checked JS docs, new Date() should return format like Fri Nov 01 2024 10:08:05 GMT+0300 (GMT+03:00)
https://www.w3schools.com/js/js_dates.asp

But looks like in K6 it works differently, I just created simple test in grafana test builder, only added console log for a date.

It also returns this formatted date: 2024-11-01T21:01:23.742Z
![image](https://github.com/user-attachments/assets/97a5affb-10fa-477c-99d0-1716092ab43f)

Run it locally and format the same
![image](https://github.com/user-attachments/assets/070123e0-15e1-4daf-897b-a1bce5632e21)

Maybe it related with date format settings, I checked on windows and ubuntu
This is a simple test:

```
import { sleep } from 'k6'
import http from 'k6/http'

export const options = {
  stages: [
    { duration: '1m', target: 1 }
  ],
}

export default function main() {
  let date = new Date();
  console.log(date);  
  sleep(10)
}
```

**Comment by AndrewASel** [comment]
I not sure, probably this docs are related with it
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format
https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format

21.4.1.32 Date Time String Format
ECMAScript defines a string interchange format for date-times based upon a simplification of the ISO 8601 calendar date extended format. The format is as follows: YYYY-MM-DDTHH:mm:ss.sssZ

**Comment by mbolotov** [comment]
Okay, I got it. 
The k6 itself and the debugger (Node.js) behave the same in fact. 
If you pass a date directly to `console.log`, it will be formatted using the ISO 8601.
if you concatenate a date with other string, the runtime will call `Date.toString()` function which returns a string in the format Thu Jan 01 1970 00:00:00 GMT+0000 (Coordinated Universal Time)

So this code prints the same for both `run` and `debug`:

```
export default function () {
    let a= new Date()
    console.log(a)
    console.log("" + a)
}
```
![image](https://github.com/user-attachments/assets/e082f45d-bd47-4591-97a5-c193b32d1ed2)
![image](https://github.com/user-attachments/assets/14dd9329-872f-4bb9-b919-cdfa55b165db)

When you look at a date object in debug evaluation view, it obviously format a date using `toString()` function:
![image](https://github.com/user-attachments/assets/6700640a-a2fb-4bf1-9e43-048a7cd6d5d3)

**Comment by mbolotov** [comment]
Hi @AndrewASel,
do you think this issue can be closed now?

**Comment by AndrewASel** [comment]
Hello @mbolotov 

I think yes it can be closed, I not able to reproduce issue now, probably because I changed timezone in PC, but there was issues related with next conversion of new Date()
For example I need to get date in this format 2024-11-10T16:21:00.000-04:00 (in local time)
I use this concationation
`convertedDate = DT.toLocaleString().slice(6, 10) + "-" + DT.toLocaleString().slice(0, 2) + "-" + DT.toLocaleString().slice(3, 5) + "T" + DT.toTimeString().slice(0, 6) + "00.000" + DT.toTimeString().slice(12, 15) + ":00";`

or to get 2024-11-10T20:21:00.000Z (in UTC time)
I use this `convertedDate = DT.toISOString().slice(0, 16) + ":00.000Z";`

In some case during debug it returns incorrect formatted string like 024-11-10T16:21:00.000-04:00
But during run of test it worked fine, I used this code over years
Unfortunately I unable to reproduce it now.

**Comment by mbolotov** [comment]
Okay, please reopen the issue if you reproduce it again
