### ISSUE TITLE
Incorrect progress bar

### ISSUE THREAD

**Issue by mbolotov** [mbolotov/k6-intellij-plugin#3]
Progress bar every time make new line
![image](https://user-images.githubusercontent.com/19785715/152566405-367fed6b-88fc-4e17-af8c-892ba9219c81.png)

Original issue: https://github.com/grafana/k6-intellij-plugin/issues/6

**Comment by toolforger** [comment]
I suspect this is because the IntelliJ terminal does not interpret the escape sequences that create the animated progress bar in Terminal.

**Comment by mbolotov** [comment]
fixed in `1.0.3` version. 
please note that the remote targets (Docker and WSL) do not support PTY terminal features so it's still an issue there.
