### ISSUE TITLE
Support K6' modules

### ISSUE THREAD

**Issue by toolforger** [mbolotov/k6-intellij-plugin#4]
Whenever I do `foo = http.post(...)`, IntelliJ complains that `http.post` is not returning a value and that that's probably an error.
The tooltip refers to a `Session.http` function, which I suspect is from NodeJS; anyway, it has a completely different signature than K6' `Session`.

**Comment by toolforger** [comment]
I have to apologize for not providing a path to a solution, as I don't know how to tell IntelliJ what library paths to use, and I don't know if K6 has even a published list of functions they provide on each object (in fact that might be different for each K6 installation, so you'd need to provide your plugin with a path to K6' executable, and somehow make that executable spit out all the relevant data that IntelliJ needs.)

**Comment by mbolotov** [comment]
Hi Joachim!
My apologizes for the late response. 
Usually, IntelliJ does recognize the k6 module type definitions (as long as they are defined as dependenices in `package.json`):
![image](https://github.com/mbolotov/k6-intellij-plugin/assets/19785715/c04818dc-eed5-4d4c-b43f-3aca9fa552bb)

However, if an IntelliJ project does not define a `module` for your source code, it will not resolve any dependencies and so does not recognize k6 type definitions. 
If it's still an issue, could you check if your project defines a module for your k6 scripts? 

You can find out if your project has a module by the presence of this sign:
![image](https://github.com/mbolotov/k6-intellij-plugin/assets/19785715/e962ff85-7ac0-4c94-8f8a-046dbabf1644)

**Comment by toolforger** [comment]
Unfortunately, I'm not working on the affected project anymore, so I can't confirm.
Thanks for the feedback though. I don't know if this is worth documenting for the plugin, or at least linking to a page that explains these dependency declarations? This would be useful for people who don't know Node's module system (like myself, I'm from a Java background and just wanted to use K6).
Feel free to close if this does not explain the issue well enough that you can actually do a fix; I have lost all mental context of what I was trying to achieve at the time, so I can't help more, unfortunately.

**Comment by mbolotov** [comment]
> I don't know if this is worth documenting for the plugin, or at least linking to a page that explains these dependency declarations?

there is an official doc page regarding this: https://k6.io/docs/misc/intellisense/

**Comment by toolforger** [comment]
Ah nice.
Maybe just put the link into the "Installation" section?

**Comment by mbolotov** [comment]
Once "Installation" section is created, I will put the link in it
