### ISSUE TITLE
support manually specifying k6 cli path

### ISSUE THREAD

**Issue by faisal6621** [mbolotov/k6-intellij-plugin#5]
The run configuration must allow specifying the path to `k6` cli.

**Comment by lcastrooliveira** [comment]
Yeah, I also think that this feature would be great.

**Comment by mbolotov** [comment]
added in `1.0.1` version:
![image](https://github.com/mbolotov/k6-intellij-plugin/assets/19785715/0edd83c5-d653-4c67-beb6-be2cebb1deec)
