### ISSUE TITLE
Impossible to run test with the help of plugin: Cannot resolve path to file

### ISSUE THREAD

**Issue by ianabogapova** [mbolotov/k6-intellij-plugin#6]
I am using plugin version 0.3.0 (installed from disk) and I expected to get a fix of this issue in the latest version but still it's impossible to start the test using plugin. The error is: "Cannot run program k6 (in directory "/Users/xxx/Projects/performance"): error=2, No such file or directory."

The same command works successfully in console.
I have Webstorm on macOS Ventura. K6 version is v0.42.0.

**Comment by mbolotov** [comment]
> The same command works successfully in console.

do you mean the exact command as it shown in the IDE run view? Or there might be any difference like full path-relative path or different current working directory?
Also, there might be some issues with different system users and permissions for the k6 launcher file.

**Comment by ianabogapova** [comment]
Here is the console command: "k6 run app/scenarios/testApplication.js"  - works fine. 

Here is setting in run configuration: 
**absolute**: /Users/yanab/Documents/Projects/performance/app/scenarios/testApplication.js - doesn't work
**relative**: app/scenarios/testApplication.js - doesn't work as well
<img width="800" alt="Screenshot 2023-02-06 at 16 40 51" src="https://user-images.githubusercontent.com/89008509/217001507-4ccc7108-f054-42ab-b15b-e97e606475e7.png">

**Comment by mbolotov** [comment]
@ianabogapova 
could you check if it works when you set the k6 installation path in the settings:
![image](https://github.com/mbolotov/k6-intellij-plugin/assets/19785715/b00af32b-0b8b-4f46-89f8-fc6150f36f4a)

**Comment by mbolotov** [comment]
closing as no response received
