### ISSUE TITLE
Unable to debug a test case

### ISSUE THREAD

**Issue by ntallapa12** [mbolotov/k6-intellij-plugin#7]
I wrote a simple k6 test case in JS and installed this plugin from marketplace. I can run the test case from IDE but unable to debug the test case. Please let me know if I am missing anything here.

**Comment by mbolotov** [comment]
Debugging from IDE requires the support from k6 engine side. So currently this is not supported.
There is a discussion on that topic: https://community.k6.io/t/how-to-debug-k6-testing-script-in-visual-studio-code/1127/10

**Comment by mbolotov** [comment]
Debugger is available starting plugin version 1.1.0
For more information, please referrer to [the guide](https://plugins.jetbrains.com/plugin/16141-k6/key-features/debugging-k6-script-by-node-js)
