### ISSUE TITLE
relative paths broken, wrong working directory

### ISSUE THREAD

**Issue by jbeckers** [mbolotov/k6-intellij-plugin#8]
This works:
![afbeelding](https://user-images.githubusercontent.com/379626/232083025-7f758cf1-183e-4374-a438-6ca160cf4420.png)

This doesn't:
![afbeelding](https://user-images.githubusercontent.com/379626/232083239-4d1a0004-f98b-4add-8ff1-fbfffbb1c976.png)

The plugin selects C:\System9\trunk\sourcesBatchKWS\VaccinnetBatchUploadCheck as the working directory, which makes no sense.

Suggested fix: allow the working directory to be specified like most run configurations do:
![afbeelding](https://user-images.githubusercontent.com/379626/232083752-a2d04b5c-85bc-4973-9b1e-c84550afa2c5.png)

**Comment by jbeckers** [comment]
Bug is most likely here
https://github.com/mbolotov/k6-intellij-plugin/blob/f435043962d6d4108273c75dde463671f062f630/src/main/kotlin/io/k6/ide/plugin/run/config.kt#L114, here https://github.com/mbolotov/k6-intellij-plugin/blob/f435043962d6d4108273c75dde463671f062f630/src/main/kotlin/io/k6/ide/plugin/run/state.kt#L80
and here https://github.com/mbolotov/k6-intellij-plugin/blob/f435043962d6d4108273c75dde463671f062f630/src/main/kotlin/io/k6/ide/plugin/actions/RunK6Action.kt#L46

**Comment by freeseacher** [comment]
+1

**Comment by mbolotov** [comment]
as of `1.0.1` version, plugin search for the project root by finding a `package.json` file going up from the current context file.
