### ISSUE TITLE
Support running under WSL

### ISSUE THREAD

**Issue by skylord123** [mbolotov/k6-intellij-plugin#9]
Would be nice to have the ability to run k6 from inside WSL. 

This can easily be done automatically by detecting if the path starts with a WSL path `\\wsl$`

Being able to run from a docker container would be nice as well.

**Comment by mbolotov** [comment]
Run on both WSL and Docker functionality was added in `1.0.1` version

**Comment by skylord123** [comment]
> Run on both WSL and Docker functionality was added in `1.0.1` version

Nice! Thanks for getting this done. I'll check it out.
